#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : qrencode
Version  : 4.1.1
Release  : 301
URL      : file:///aot/build/clearlinux/packages/qrencode/qrencode-v4.1.1.tar.gz
Source0  : file:///aot/build/clearlinux/packages/qrencode/qrencode-v4.1.1.tar.gz
Summary  : A QR Code encoding library
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
BuildRequires : SDL2
BuildRequires : SDL2-dev
BuildRequires : buildreq-cmake
BuildRequires : libpng-dev
BuildRequires : libpng-staticdev
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(sdl2)

%description
# libqrencode - a fast and compact QR Code encoding library
[![build](https://github.com/fukuchi/libqrencode/workflows/build/badge.svg)](https://github.com/fukuchi/libqrencode/actions)

%prep
%setup -q -n qrencode
cd %{_builddir}/qrencode

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1639861317
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=16 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=16 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=16 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=16 "
sd -r '\s--dirty\s' ' ' .
sd -r 'git describe' 'git describe --abbrev=0' .
%autogen
make  %{?_smp_mflags}    V=1 VERBOSE=1


%check
export LANG=C.UTF-8
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1639861317
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
