#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : qrencode
Version  : 4.1.0
Release  : 3
URL      : https://fukuchi.org/works/qrencode/qrencode-4.1.0.tar.gz
Source0  : https://fukuchi.org/works/qrencode/qrencode-4.1.0.tar.gz
Summary  : A QR Code encoding library
Group    : Development/Tools
License  : LGPL-2.1
Requires: qrencode-bin = %{version}-%{release}
Requires: qrencode-lib = %{version}-%{release}
Requires: qrencode-license = %{version}-%{release}
Requires: qrencode-man = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(sdl2)

%description
libqrencode - a fast and compact QR Code encoding library
GENERAL INFORMATION
===================
Libqrencode is a fast and compact library for encoding data in a QR Code,
a 2D symbology that can be scanned by handy terminals such as a smartphone.
The capacity of QR Code is up to 7000 digits or 4000 characters and has high
robustness.

%package bin
Summary: bin components for the qrencode package.
Group: Binaries
Requires: qrencode-license = %{version}-%{release}

%description bin
bin components for the qrencode package.


%package dev
Summary: dev components for the qrencode package.
Group: Development
Requires: qrencode-lib = %{version}-%{release}
Requires: qrencode-bin = %{version}-%{release}
Provides: qrencode-devel = %{version}-%{release}
Requires: qrencode = %{version}-%{release}

%description dev
dev components for the qrencode package.


%package lib
Summary: lib components for the qrencode package.
Group: Libraries
Requires: qrencode-license = %{version}-%{release}

%description lib
lib components for the qrencode package.


%package license
Summary: license components for the qrencode package.
Group: Default

%description license
license components for the qrencode package.


%package man
Summary: man components for the qrencode package.
Group: Default

%description man
man components for the qrencode package.


%prep
%setup -q -n qrencode-4.1.0
cd %{_builddir}/qrencode-4.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1598905169
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1598905169
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qrencode
cp %{_builddir}/qrencode-4.1.0/COPYING %{buildroot}/usr/share/package-licenses/qrencode/9a1929f4700d2407c70b507b3b2aaf6226a9543c
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/qrencode

%files dev
%defattr(-,root,root,-)
/usr/include/qrencode.h
/usr/lib64/libqrencode.so
/usr/lib64/pkgconfig/libqrencode.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libqrencode.so.4
/usr/lib64/libqrencode.so.4.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qrencode/9a1929f4700d2407c70b507b3b2aaf6226a9543c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/qrencode.1
